input:
  folder: ./data/in
  columns_to_keep:
    - col_a
    - tbd

train:
  experiment_name: default
  model_type: classifier
  random_state: 42
  target_name: target
  test_size: 0.2

output:
  folder: ./data/out

logging:
  date_format: '%Y-%m-%d %H:%M:%S'
  format: '[%(asctime)s] %(message)s'
  level: INFO


